[package]
name = "utocli"
authors.workspace = true
description = "Auto-generate OpenCLI specifications"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
utocli-core = { path = "../utocli-core" }

[lints]
workspace = true
