[package]
name = "utocli-derive"
authors.workspace = true
description = "Derive macros for utocli"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]

[lints]
workspace = true
